### ISSUE TITLE
aggiungere dati elezioni Marche

### ISSUE THREAD

**Issue by aborruso** [ondata/elezioni_2020#3]
In particolare `anagrRagrupp` da `https://dati.elezioni.marche.it/static_json/raggrup_0_100.json`

E votiRaggrup da tutti e 228 i comuni, quindi da `https://dati.elezioni.marche.it/static_json/raggrup_0_{1..228}json`

@gjrichter confermi?

**Comment by gjrichter** [comment]
giusto!

**Comment by aborruso** [comment]
@gjrichter ecco i due file:

- https://github.com/ondata/elezioni_2020/blob/master/regionaliMarche/processing/anagrRaggrup.csv
- https://github.com/ondata/elezioni_2020/blob/master/regionaliMarche/processing/votiRaggrup-arrVotiRaggrup.csv

**Comment by gjrichter** [comment]
@aborruso perfetto! 

per i file di prima ho visto solo che manca il idComune 1 nella sequenza dei comuni 1 .. 228 (votiListe-arrVotiListe.csv)

**Comment by aborruso** [comment]
> per i file di prima ho visto solo che manca il idComune 1 nella sequenza dei comuni 1 .. 228 (votiListe-arrVotiListe.csv)

Corretto, grazie

**Comment by gjrichter** [comment]
grazie a te
